### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by ascclemens** [rustls/hyper-rustls#20]
Reference to https://github.com/ctz/rustls/issues/22.

Having `log` be an optional crate is great in `rustls`. However, *this* crate depends on `rustls` with no way to turn off logging, which really, really looks bad in binary crates (especially since `rustls` prints out all of this debug info in the `INFO` log level instead of `DEBUG`).

Please either make logging an option here or turn it off.

**Comment by lucab** [comment]
However, as `logging` is a default feature of rustls, in order to turn it off you'll need to go after every single dependency of your project and convince them to opt-out or expose a feature. I don't think this will scale out well. Some alternatives could be:
 * use slog to [disable chatty levels at compile time](https://github.com/slog-rs/slog/wiki/FAQ#can-i-disable-some-logging-levels-at-compile-time)
 * make logging a non-default feature in rustls (i.e. opt-in)
 * adjust log [max_levels](https://github.com/rust-lang-nursery/log/pull/165)
 * wait for log to catch on with slog level and build-time stubbing

**Comment by jkcclemens** [comment]
Making logging non-default in `rustls` would be good, as this is generally what's expected of that kind of library, and I'm surprised this isn't already the case.

Having `rustls = { version = "whatever", no-default-features = true }` is still possible in this crate, as well. Can definitely have a feature that enables it or disables it, as well.

**Comment by g2p** [comment]
Fixed in #156
